Update ci-build.yml

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -40,6 +40,10 @@ jobs:
       - name: Clone
         uses: actions/checkout@v4
 
+      - name: Show clang-format version
+        run: |
+          clang-format --version
+
       - name: clang-format
         run: find src -type f -name \*.cc -o -name \*.h | xargs clang-format --dry-run --Werror
 
@@ -80,17 +84,21 @@ jobs:
           cd os/android
           ./gradlew assembleDebug
 
+      - name: Change apk file name
+        run: |
+          mv os/android/app/build/outputs/apk/debug/app-debug.apk os/android/app/build/outputs/apk/debug/fallout2-ce.apk
+
       - name: Upload
         uses: actions/upload-artifact@v4
         with:
           name: fallout2-ce-debug.apk
-          path: os/android/app/build/outputs/apk/debug/app-debug.apk
+          path: os/android/app/build/outputs/apk/debug/fallout2-ce.apk
           retention-days: 7
 
   ios:
     name: iOS
 
-    runs-on: macos-13
+    runs-on: macos-14
 
     steps:
       - name: Clone
@@ -165,11 +173,15 @@ jobs:
         run: |
           cmake --build --preset linux-${{ matrix.arch }}-debug
 
+      - name: Change executable file name
+        run: |
+          mv out/build/linux-${{ matrix.arch }}-debug/fallout2-ce out/build/linux-${{ matrix.arch }}-debug/fallout2-ce-linux-${{ matrix.arch }}
+
       - name: Upload
         uses: actions/upload-artifact@v4
         with:
           name: fallout2-ce-linux-${{ matrix.arch }}
-          path:  out/build/linux-${{ matrix.arch }}-debug/fallout2-ce
+          path:  out/build/linux-${{ matrix.arch }}-debug/fallout2-ce-linux-${{ matrix.arch }}
           retention-days: 7
 
   linux-armhf:
@@ -201,11 +213,15 @@ jobs:
       - name: Build
         run: cmake --build build
 
+      - name: Change executable file name
+        run: |
+          mv build/fallout2-ce build/fallout2-ce-linux-armhf
+
       - name: Upload
         uses: actions/upload-artifact@v4
         with:
           name: fallout2-ce-linux-armhf
-          path:  build/fallout2-ce
+          path:  build/fallout2-ce-linux-armhf
           retention-days: 7
 
   linux-arm64:
@@ -228,17 +244,21 @@ jobs:
       - name: Build
         run: cmake --build build
 
+      - name: Change executable file name
+        run: |
+          mv build/fallout2-ce build/fallout2-ce-linux-arm64
+
       - name: Upload
         uses: actions/upload-artifact@v4
         with:
           name: fallout2-ce-linux-arm64
-          path:  build/fallout2-ce
+          path:  build/fallout2-ce-linux-arm64
           retention-days: 7
 
   macos:
     name: macOS
 
-    runs-on: macos-13
+    runs-on: macos-14
 
     steps:
       - name: Clone
@@ -300,11 +320,87 @@ jobs:
 
       - name: Build
         run: |
-          cmake --build --preset windows-${{ matrix.arch }}-debug
+          cmake --build --preset windows-${{ matrix.arch }}-release
+
+      - name: Change executable file name
+        run: |
+          mv out/build/windows-${{ matrix.arch }}/RelWithDebInfo/fallout2-ce.exe out/build/windows-${{ matrix.arch }}/RelWithDebInfo/fallout2-ce-${{ matrix.arch }}.exe
 
       - name: Upload
         uses: actions/upload-artifact@v4
         with:
           name: fallout2-ce-windows-${{ matrix.arch }}
-          path:  out/build/windows-${{ matrix.arch }}/Debug/fallout2-ce.exe
+          path:  out/build/windows-${{ matrix.arch }}/RelWithDebInfo/fallout2-ce-${{ matrix.arch }}.exe
           retention-days: 7
+
+
+  release:
+    name: Release Continuous build
+    runs-on: ubuntu-latest
+    needs: [android, ios, linux, linux-armhf, linux-arm64, macos, windows]
+    permissions: write-all
+    steps:
+      - name: Fetch artifacts
+        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
+        uses: actions/download-artifact@v4.1.7
+        with:
+          path: artifacts/
+
+      - name: Remove old release
+        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
+        uses: dev-drprasad/delete-tag-and-release@v0.2.1
+        with:
+          delete_release: true
+          tag_name: continious
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Move unpacked artifacts to root folder
+        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
+        run: |
+          ls -Rlah .
+          find .
+          cd artifacts/
+          for folder in *; do
+            if [[ -d "$folder" && "$folder" != "." ]]; then
+              echo "Processing $folder"
+              mv "$folder" "$folder.dir"
+              cd "$folder.dir"
+              for file in *; do
+                if [ -f "$file" ]; then
+                  if [ -f "../$file" ]; then
+                    echo "ERROR: Duplicate artifact file name $file"
+                    exit 1
+                  fi
+                  if [ -d "../$file" ]; then
+                    echo "ERROR: Duplicate artifact folder $file"
+                    exit 1
+                  fi
+
+                  echo "Moving $file"
+                  mv "$file" "../$file"
+                fi
+              done
+              cd ..
+              rm -rf "$folder.dir"
+            fi
+          done
+          ls -Rlah .
+          find .
+          cd ../
+
+      - name: Allow GitHub to process removed release for few seconds
+        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
+        run: |
+          sleep 20s
+
+      - name: Upload new release
+        if: ${{ always() && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
+        uses: softprops/action-gh-release@v0.1.15
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          files: artifacts/*
+          tag_name: continious
+          draft: false
+          prerelease: true
+          name: Fallout2-CE Continuous Build
